[general]
import = [
    # "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
    "~/.config/alacritty/themes/themes/rose_pine.toml"
]

[terminal.shell]
program = "/usr/bin/fish"
args = ["-l"]


[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 11 # Ajusta el tamaño de la fuente según tu preferencia

