theme= "gruvbox_dark_hard"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.file-picker]
hidden = false
git-ignore = true

[editor.soft-wrap]
enable = true
wrap-indicator = "↪ "      # Símbolo visual que indica que la línea está cortada (ej: "↪ ", "↳ ", "↵ ")
max-wrap = 25              # Sangría máxima para el texto envuelto
wrap-at-text-width = false # false = corta en el borde de la ventana; true = corta en text-width (ej: columna 80)

[keys.normal]
C-d = ["page_cursor_half_down", "align_view_center"]
C-u = ["page_cursor_half_up", "align_view_center"]
