[language-server.tinymist]
command = "tinymist"
config = { preview.background.enabled = true, preview.background.args = ["--data-plane-host=127.0.0.1:0", "--open"], preview.scrollSync = "onSelectionChange" }

[[language]]
name = "typst"
language-servers = [ "tinymist" ]
auto-format = true
